### ISSUE TITLE
Concat + Audio missing.

### ISSUE THREAD

**Issue by kishorevaishnav** [u2takey/ffmpeg-go#52]
@u2takey For some reason, the audio is getting lost during concat.

I tried the example you mentioned [here](https://github.com/u2takey/ffmpeg-go/issues/35#issuecomment-1013655829) and lost the audio completely on the `concat.mp4` even though I had perfect audio on the two files.

Here is my version of the code, still the audio is not working - note the Video is completely fine:
```
// Lets concate everything.
finalFiles := []*ffmpeg.Stream{}
for _, file := range listFiles() {
	finalFiles = append(finalFiles, ffmpeg.Input(file.Name()))
}

ffmpeg.Concat(finalFiles).
	Output("w_final.mp4").
	OverWriteOutput().
	ErrorToStdOut().
	Run()
```

If I modify the command output (by adding `:a=1`) & execute on command line it works perfectly fine:
`ffmpeg -i ./w_one.mp4 -i ./w_two.mp4 -i ./w_three.mp4 -filter_complex "[0][1][2]concat=n=3[s0]" -map "[s0]" ./concat.mp4 -y`
to 
`ffmpeg -i ./w_one.mp4 -i ./w_two.mp4 -i ./w_three.mp4 -filter_complex "[0][1][2]concat=n=3:a=1[s0]" -map "[s0]" ./concat.mp4 -y`

Please let me know where to add these parameter to make it work? Though I tried this below and it doesn't work, instead it throws an error
```
ffmpeg.Concat(finalFiles, ffmpeg.KwArgs{"a": "1"}).
```
Error:
```
panic: interface conversion: interface {} is string, not int

goroutine 1 [running]:
github.com/u2takey/ffmpeg-go.Concat({0x140000d2ea0, 0x3, 0x4}, {0x1400019fdf0, 0x1, 0x100e84ee8?})
        /Users/kishore/go/pkg/mod/github.com/u2takey/ffmpeg-go@v0.4.1/filters.go:108 +0x2d0
main.main()
        /Users/kishore/proj/github.com/kishorevaishnav/hotbrain/main.go:120 +0x158
exit status 2
```

**Comment by Tnemlec** [comment]
Hello,

Maybe take a look at this issue #39 , hope this will help :smile:
